version: 2.1
jobs:
  build:
    working_directory: ~/FrontEnd/myfirstapp
    docker:
      - image: circleci/node:12.18.1
    steps:
      - checkout
      - run: ls
      - run: pwd
      - run: npm install --save
      - run: npm start
      