version: 2.1
jobs:
  build:
    working_directory: ~/BackEnd
    docker:
      - image: circleci/node:12.18.1
    steps:
      - checkout:
          path: ~/BackEnd
      - run: npm install --save
      - run: npm start