version: 2.1
jobs:
  buildFront:
    working_directory: ~/major-assignment/FrontEnd/myfirstapp
    docker:
      - image: circleci/node:12.18.1
    steps:
      - checkout:
          path: ~/major-assignment
      - run: ls
      - run: pwd
      - run: npm install --save
      - run: npm start
  buildBack:
    working_directory: ~/major-assignment/BackEnd/loginmicroservices
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout:
          path: ~/major-assignment
      - run: chmod +x ./mvnw
      - run: ./mvnw package
      - run: java -jar target/loginmicroservices-0.0.1.jar     
workflows:
  version: 2
  build_and_test:
    jobs:
      - buildFront
      - buildBack